#!/bin/bash -e

cd $(dirname $0)/..

ENV=${1:-test}
echo "Deploying Elasticsearch with config for environment: ${ENV}..."

kubectl apply -f elasticsearch/es-configmap.yaml
kubectl apply -f elasticsearch/es-service.yaml
kubectl apply -f elasticsearch/es-statefulset.yaml
kubectl patch statefulset es-cluster -n efk -p '{"spec":{"template":{"metadata":{"annotations":{"timestamp": '\"$(date +'%s')\"' }}}}}'
kubectl rollout status statefulset/es-cluster -n efk
